// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "adr/adr-0001-modular-bloc.mdx": () => import("../content/docs/adr/adr-0001-modular-bloc.mdx?collection=docs"), "adr/index.mdx": () => import("../content/docs/adr/index.mdx?collection=docs"), "api-contracts/inventory.mdx": () => import("../content/docs/api-contracts/inventory.mdx?collection=docs"), "api-contracts/overview.mdx": () => import("../content/docs/api-contracts/overview.mdx?collection=docs"), "api-contracts/versioning.mdx": () => import("../content/docs/api-contracts/versioning.mdx?collection=docs"), "architecture/components.mdx": () => import("../content/docs/architecture/components.mdx?collection=docs"), "architecture/data-models.mdx": () => import("../content/docs/architecture/data-models.mdx?collection=docs"), "architecture/endpoints.mdx": () => import("../content/docs/architecture/endpoints.mdx?collection=docs"), "architecture/flows.mdx": () => import("../content/docs/architecture/flows.mdx?collection=docs"), "architecture/overview.mdx": () => import("../content/docs/architecture/overview.mdx?collection=docs"), "architecture/screens.mdx": () => import("../content/docs/architecture/screens.mdx?collection=docs"), "operations/environments.mdx": () => import("../content/docs/operations/environments.mdx?collection=docs"), "operations/incident-runbook.mdx": () => import("../content/docs/operations/incident-runbook.mdx?collection=docs"), "operations/release-runbook.mdx": () => import("../content/docs/operations/release-runbook.mdx?collection=docs"), "product/overview.mdx": () => import("../content/docs/product/overview.mdx?collection=docs"), "quality/pr-checklist.mdx": () => import("../content/docs/quality/pr-checklist.mdx?collection=docs"), "quality/testing-strategy.mdx": () => import("../content/docs/quality/testing-strategy.mdx?collection=docs"), "security/lgpd.mdx": () => import("../content/docs/security/lgpd.mdx?collection=docs"), "security/secrets-and-access.mdx": () => import("../content/docs/security/secrets-and-access.mdx?collection=docs"), "setup/installation.mdx": () => import("../content/docs/setup/installation.mdx?collection=docs"), "setup/running.mdx": () => import("../content/docs/setup/running.mdx?collection=docs"), "state-management/inventory.mdx": () => import("../content/docs/state-management/inventory.mdx?collection=docs"), "state-management/overview.mdx": () => import("../content/docs/state-management/overview.mdx?collection=docs"), }),
};
export default browserCollections;